#  Deep Learning and Image Recognition

## Introduction to Tensorflow 2.0

TensorFlow is a graph computing library open-sourced by Google and primarily used for Deep Learning.

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
#Version
print("TensorFlow version: {}".format(tf.__version__))

#In Tensorflow 2.0, eager execution is enabled by default.
print("Eager execution: {}".format(tf.executing_eagerly()))

TensorFlow version: 2.1.0
Eager execution: True


### Hello World 

In [3]:
message = tf.constant('Hello, TensorFlow!')

In [4]:
message

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello, TensorFlow!'>

In [6]:
message.dtype

tf.string

### Constants

In [5]:
t = tf.constant(2)
t

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [6]:
t.shape

TensorShape([])

In [7]:
t.dtype

tf.int32

In [8]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [9]:
t.shape

TensorShape([2, 3])

In [10]:
t.dtype

tf.float32

### Indexing

In [11]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [12]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [13]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [14]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [15]:
#t @ tf.transpose(t)

In [16]:
# Basic constant operations
# The value returned by the constructor represents the output of the Constant op.
a = tf.constant(2)
b = tf.constant(3)

In [17]:
#Prints the nodes of the computational graph within a session. 
print ("a:", a, ", b:", b)

#Perform arithmetic operations 
print ("a + b = %i" % (a+b))
print ("a * b = %i" % (a*b))

a: tf.Tensor(2, shape=(), dtype=int32) , b: tf.Tensor(3, shape=(), dtype=int32)
a + b = 5
a * b = 6


### Numpy Vs Tensorflow

In [18]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [19]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]])>

In [20]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

### Conflicting Types

In [21]:
try:
    tf.constant(1) + tf.constant(1.0)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: add/


In [25]:
try:
    tf.constant(1, dtype=tf.float64) + tf.constant(1.0)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:AddV2] name: add/


In [24]:
try:
    tf.constant(1, dtype=tf.float32) + tf.constant(1.0)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

### Variables

In [23]:
a = tf.constant(35, name='a')
b = tf.Variable(a + 5, name='b')

#Perform arithmetic operations 
print ("a + b = %i" % (a+b))
print ("a * b = %i" % (a*b))

a + b = 75
a * b = 1400


In [24]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [25]:
v.value()

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [26]:
v.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [27]:
v.assign(2 * v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

### Ragged Constants

Ragged tensors are the TensorFlow equivalent of nested variable-length lists. They make it easy to store and process data with non-uniform shapes

In [28]:
digits = tf.ragged.constant([[3, 1, 4, 1], [], [5, 9, 2], [6], []])
print(tf.add(digits, 3))
print(tf.reduce_mean(digits, axis=1))
print(tf.concat([digits, [[5, 3]]], axis=0))
print(tf.tile(digits, [1, 2]))

<tf.RaggedTensor [[6, 4, 7, 4], [], [8, 12, 5], [9], []]>
tf.Tensor([2.25              nan 5.33333333 6.                nan], shape=(5,), dtype=float64)
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], [], [5, 3]]>
<tf.RaggedTensor [[3, 1, 4, 1, 3, 1, 4, 1], [], [5, 9, 2, 5, 9, 2], [6, 6], []]>


In [29]:
words = tf.ragged.constant([["So", "long"], ["thanks", "for", "all", "the", "fish"]])
print(tf.strings.substr(words, 0, 2))

<tf.RaggedTensor [[b'So', b'lo'], [b'th', b'fo', b'al', b'th', b'fi']]>


### Devices

In [26]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 7145806828542520877
, name: "/device:XLA_CPU:0"
device_type: "XLA_CPU"
memory_limit: 17179869184
locality {
}
incarnation: 17017953121188393959
physical_device_desc: "device: XLA_CPU device"
]


In [15]:
with tf.device("/cpu:0"):
    t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [16]:
t.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [17]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        t2 = tf.constant([[1., 2., 3.], [4., 5., 6.]])
    print(t2.device)

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
/job:localhost/replica:0/task:0/device:GPU:0


    
          
    with tf.device('/gpu:0'):
        a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
        b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
        c = tf.matmul(a, b)
    print(c.device)

### The tf.function decorator

When you annotate a function with tf.function, you can still call it like any other function. But it will be compiled into a graph, which means you get the benefits of faster execution, running on GPU or TPU, or exporting to SavedModel.

In [18]:
# Define some operations
@tf.function
def add(x, y):
    return tf.add(x, y)

@tf.function
def multiply(x, y):
    return tf.multiply(x, y)

print ("add node :", add)
print ("mul node :", multiply, "\n")

add node : <tensorflow.python.eager.def_function.Function object at 0x0000013BC7EF2088>
mul node : <tensorflow.python.eager.def_function.Function object at 0x0000013BC7EF2A08> 



In [19]:
a = 2
b = 3

print ("a :", a)
print ("b :", b)


# Run operations with variable input
print ("a + b = %i" % add(a, b))
print ("a * b = %i" % multiply(a, b))

a : 2
b : 3
a + b = 5
a * b = 6


In [36]:
W = tf.Variable(tf.ones(shape=(2,2)), name="W")
b = tf.Variable(tf.zeros(shape=(2)), name="b")

@tf.function
def forward(x):
  return W * x + b

out_a = forward([1,0])

print(out_a)

tf.Tensor(
[[1. 0.]
 [1. 0.]], shape=(2, 2), dtype=float32)


In [37]:
@tf.function
def simple_nn_layer(x, y):
  return tf.nn.relu(tf.matmul(x, y))

x = tf.random.uniform((3, 3))
y = tf.random.uniform((3, 3))

simple_nn_layer(x, y)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6920842 , 1.121564  , 0.9563033 ],
       [0.82643735, 1.2718791 , 1.1814188 ],
       [0.87981653, 1.2965035 , 1.3139201 ]], dtype=float32)>

### API - Reduce Functions

In [38]:
x = tf.constant([[1, 1, 1], [1, 1, 1]])

print(tf.reduce_sum(x))  # 6
print(tf.reduce_sum(x, 0))  # [2, 2, 2]
print(tf.reduce_sum(x, 1))  # [3, 3]
print(tf.reduce_sum(x, [0, 1]))  # 6

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([2 2 2], shape=(3,), dtype=int32)
tf.Tensor([3 3], shape=(2,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


Reduce Mean compared to Numpy

In [39]:
c = np.array([[3.,4], [5.,6], [6.,7]])
print(np.mean(c,1))

tf.reduce_mean(c,1)

[3.5 5.5 6.5]


<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3.5, 5.5, 6.5])>

### Matrices

In [40]:
# Create a Constant op that produces a 1x2 matrix.  The op is
# added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.

matrix1 = tf.constant([[3., 3.]])
print (matrix1)

tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)


In [41]:
# Create another Constant that produces a 2x1 matrix.
matrix2 = tf.constant([[2.],[2.]])
print (matrix2)

tf.Tensor(
[[2.]
 [2.]], shape=(2, 1), dtype=float32)


In [42]:
# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.
product = tf.linalg.matmul(matrix1, matrix2)

product

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>